
export const categoryList = [
    {title: "Pizza", value: "pizza"},
    {title: "Biryani", value: "biryani"},
    {title: "Dosa", value: "dosa"},
    {title: "Momos", value: "momos"},
    {title: "Khichdi", value: "khichdi"},
    {title: "Vada Pav", value: "vada pav"},
    {title: "Kachori", value: "kachori"},
    {title: "Chaach", value: "chaach"},
    {title: "Cold Coffee", value: "cold coffee"},
    {title: "Upma", value: "upma"},
    {title: "Soup", value: "soup"},
    {title: "Poori Bhaji", value: "poori bhaji"},
    {title: "Aloo Poori", value: "aloo poori"},
    {title: "Bhel", value: "bhel"},
    {title: "Masala Maggi", value: "masala maggi"},
    {title: "Cookies", value: "cookies"},
    {title: "Dabeli", value: "dabeli"},
    {title: "Pakoda", value: "pakoda"},
    {title: "Korma", value: "korma"},
    {title: "Hot Dog", value: "hot dog"},
    {title: "Poha", value: "poha"},
    {title: "Thepla", value: "thepla"},
    {title: "Aloo Tikki", value: "aloo tikki"},
    {title: "Parotta", value: "parotta"},
    {title: "Falooda", value: "falooda"},
    {title: "Ramen", value: "ramen"},
    {title: "Cake", value: "cake"},
    {title: "Burger", value: "burger"},
    {title: "Sandwich", value: "sandwich"},
    {title: "Paneer", value: "paneer"},
    {title: "Idli", value: "idli"},
    {title: "Noodles", value: "noodles"},
    {title: "Paratha", value: "paratha"},
    {title: "Ice Cream", value: "ice cream"},
    {title: "Chaat", value: "chaat"},
    {title: "Milkshake", value: "milkshake"},
    {title: "Manchurian", value: "manchurian"},
    {title: "Sev Tamatar", value: "sev tamatar"},
    {title: "Dhokla", value: "dhokla"},
    {title: "Pav Bhaji", value: "pav bhaji"},
    {title: "Samosa", value: "samosa"},
    {title: "Tea", value: "tea"},
    {title: "Juice", value: "juice"},
    {title: "Pasta", value: "pasta"},
    {title: "Coffee", value: "coffee"},
    {title: "Lassi", value: "lassi"},
    {title: "Bread Pakoda", value: "bread pakoda"},
    {title: "Desserts", value: "desserts"},
    {title: "Khaman", value: "khaman"},
    {title: "Salad", value: "salad"},
    {title: "Gulab Jamun", value: "gulab jamun"},
    {title: "Rasmalai", value: "rasmalai"},
    {title: "Sev Khamani", value: "sev khamani"},
    {title: "Pancake", value: "pancake"},
    {title: "Cheesecake", value: "cheesecake"},
    {title: "Vada", value: "vada"},
    {title: "Masala Poori", value: "masala poori"},
    {title: "Jalebi", value: "jalebi"},
    {title: "Khandvi", value: "khandvi"},
    {title: "Panipuri", value: "panipuri"},
    {title: "Dal Kachori", value: "dal kachori"},
    {title: "Fafda", value: "fafda"},
    {title: "Sav poori", value: "sav poori"},
    {title: "Chocolate", value: "chocolate"},
]

