import img1 from '../assets/Category img/Thali.png';
import img2 from '../assets/Category img/pizza.png';
import img3 from '../assets/Category img/Biryani.png';
import img4 from '../assets/Category img/Chole Bhature.png';
import img5 from '../assets/Category img/North Indian.png';
import img6 from '../assets/Category img/Dosa.png';
import img7 from '../assets/Category img/gujarati.webp';
import img8 from '../assets/Category img/8.png';
import img9 from '../assets/Category img/7.png';

export const categoryList = [
    {title: "Thali", value: "thali", img: img1},
    {title: "Pizza", value: "pizza", img: img2},
    {title: "Biryani", value: "biryani", img: img3},
    {title: "Chole Bhature", value: "chole bhature", img: img4},
    {title: "North Indian", value: "north indian", img: img5},
    {title: "Dosa", value: "dosa", img: img6},
    {title: "Gujarati", value: "gujarati", img: img7},
    {title: "Wraps", value: "wraps", img: img8},
    {title: "Fried Rice", value: "fried rice", img: img9},
    {title: "Rajasthani", value: "rajasthani", img: img6},
    {title: "Momos", value: "momos", img: img6},
    {title: "South Indian", value: "south indian", img: img6},
    {title: "Fries", value: "fries", img: img6},
    {title: "Khichdi", value: "khichdi", img: img6},
    {title: "Dal", value: "dal", img: img6},
    {title: "Shawarma", value: "shawarma", img: img6},
    {title: "Pastry", value: "pastry", img: img6},
    {title: "Vada Pav", value: "vada pav", img: img6},
    {title: "Kachori", value: "kachori", img: img6},
    {title: "Chaach", value: "chaach", img: img6},
    {title: "Chole Kulche", value: "chole kulche", img: img6},
    {title: "Cold Coffee", value: "cold coffee", img: img6},
    {title: "Upma", value: "upma", img: img6},
    {title: "Soup", value: "soup", img: img6},
    {title: "Chaap", value: "chaap", img: img6},
    {title: "Tiramisu", value: "tiramisu", img: img6},
    {title: "Halwa", value: "halwa", img: img6},
    {title: "Poori Bhaji", value: "poori bhaji", img: img6},
    {title: "Sub", value: "sub", img: img6},
    {title: "Sundae", value: "sundae", img: img6},
    {title: "Aloo Poori", value: "aloo poori", img: img6},
    {title: "Tacos", value: "tacos", img: img6},
    {title: "Puff Pastry", value: "puff pastry", img: img6},
    {title: "Rajma Rice", value: "rajma rice", img: img6},
    {title: "Bhel", value: "bhel", img: img6},
    {title: "Tart", value: "tart", img: img6},
    {title: "Rasgulla", value: "rasgulla", img: img6},
    {title: "Lasagne", value: "lasagne", img: img6},
    {title: "Falafel", value: "falafel", img: img6},
    {title: "Pudding", value: "pudding", img: img6},
    {title: "Masala Maggi", value: "masala maggi", img: img6},
    {title: "Cookies", value: "cookies", img: img6},
    {title: "Dabeli", value: "dabeli", img: img6},
    {title: "Satay", value: "satay", img: img6},
    {title: "Mausse", value: "mausse", img: img6},
    {title: "Pie", value: "pie", img: img6},
    {title: "Muffin", value: "muffin", img: img6},
    {title: "Brawnie", value: "brawnie", img: img6},
    {title: "Bhurji", value: "bhurji"},
    {title: "Pakoda", value: "pakoda"},
    {title: "Korma", value: "korma"},
    {title: "Hot Dog", value: "hot dog"},
    {title: "Poha", value: "poha"},
    {title: "Bowl", value: "bowl"},
    {title: "Thepla", value: "thepla"},
    {title: "Dahi Bhalle", value: "dahi bhalle"},
    {title: "Aloo Tikki", value: "aloo tikki"},
    {title: "Paneer Kulche", value: "paneer kulche"},
    {title: "Appam", value: "appam"},
    {title: "Chole Poori", value: "chole poori"},
    {title: "Raj Kachori", value: "raj kachori"},
    {title: "Paneer Pakoda", value: "paneer pakoda"},
    {title: "Curd Rice", value: "curd rice"},
    {title: "Parotta", value: "parotta"},
    {title: "Falooda", value: "falooda"},
    {title: "Granola", value: "granola"},
    {title: "Enchilada", value: "enchilada"},
    {title: "Ramen", value: "ramen"},
    {title: "Pongal", value: "pongal"},
    {title: "Dimsums", value: "dimsums"},
    {title: "Cake", value: "cake"},
    {title: "Burger", value: "burger"},
    {title: "Sandwich", value: "sandwich"},
    {title: "Paneer", value: "paneer"},
    {title: "Idli", value: "idli"},
    {title: "Tiffin", value: "tiffin"},
    {title: "Noodles", value: "noodles"},
    {title: "Paratha", value: "paratha"},
    {title: "Ice Cream", value: "ice cream"},
    {title: "Chaat", value: "chaat"},
    {title: "Milkshake", value: "milkshake"},
    {title: "Manchurian", value: "manchurian"},
    {title: "Sev Tamatar", value: "sev tamatar"},
    {title: "Dhokla", value: "dhokla"},
    {title: "Pav Bhaji", value: "pav bhaji"},
    {title: "Samosa", value: "samosa"},
    {title: "Tea", value: "tea"},
    {title: "Juice", value: "juice"},
    {title: "Pasta", value: "pasta"},
    {title: "Coffee", value: "coffee"},
    {title: "Khulche", value: "khulche"},
    {title: "Pulao", value: "pulao"},
    {title: "Waffles", value: "waffles"},
    {title: "Lassi", value: "lassi"},
    {title: "Bread Pakoda", value: "bread pakoda"},
    {title: "Desserts", value: "desserts"},
    {title: "Pyaaj Kachori", value: "pyaaj kachori"},
    {title: "Khaman", value: "khaman"},
    {title: "Salad", value: "salad"},
    {title: "Gulab Jamun", value: "gulab jamun"},
    {title: "Poori", value: "poori"},
    {title: "Gelato", value: "gelato"},
    {title: "Cupcake", value: "cupcake"},
    {title: "Sizzler", value: "sizzler"},
    {title: "Veg Meal", value: "veg meal"},
    {title: "Misal Pav", value: "misal pav"},
    {title: "Rasmalai", value: "rasmalai"},
    {title: "Nachos", value: "nachos"},
    {title: "Sev Khamani", value: "sev khamani"},
    {title: "Burrito", value: "burrito"},
    {title: "Cutlet", value: "cutlet"},
    {title: "Doughnut", value: "doughnut"},
    {title: "Croissant", value: "croissant"},
    {title: "Chop Suey", value: "chop suey"},
    {title: "Uttapam", value: "uttapam"},
    {title: "Quesadilla", value: "quesadilla"},
    {title: "Pancake", value: "pancake"},
    {title: "Kofta", value: "kofta"},
    {title: "Mushrooms", value: "mushrooms"},
    {title: "Cheesecake", value: "cheesecake"},
    {title: "Vada", value: "vada"},
    {title: "Kebabs", value: "kebabs"},
    {title: "Masala Poori", value: "masala poori"},
    {title: "Jalebi", value: "jalebi"},
    {title: "Khandvi", value: "khandvi"},
    {title: "Malai Kafta", value: "malai kafta"},
    {title: "Chur Chur Naan", value: "chur chur naan"},
    {title: "Veg Lollipop", value: "veg lollipop"},
    {title: "Panipuri", value: "panipuri"},
    {title: "Dal Kachori", value: "dal kachori"},
    {title: "Sev Usal", value: "sev usal"},
    {title: "Fafda", value: "fafda"},
    {title: "Sav poori", value: "sav poori"},
    {title: "Chocolate", value: "chocolate"},
    {title: "Risotto", value: "risotto"},
    {title: "Ravioli", value: "ravioli"},
    {title: "Bao", value: "bao"},
    {title: "Stew", value: "stew"},
    {title: "Sushi", value: "sushi"},
    {title: "Moong Pakoda", value: "moong pakoda"},
]