import img2 from '../assets/Category img/pizza.png';
import img3 from '../assets/Category img/Biryani.png';
import img6 from '../assets/Category img/Dosa.png';
import img1 from '../assets/Category img/9.png';
import img4 from '../assets/Category img/10.png';
import img5 from '../assets/Category img/11.png';
import img7 from '../assets/Category img/12.png';
import img8 from '../assets/Category img/13.png';
import img9 from '../assets/Category img/14.png';

export const categoryList = [
    {title: "Pizza", value: "pizza", img: img2},
    {title: "Biryani", value: "biryani", img: img3},
    {title: "Dosa", value: "dosa", img: img6},
    {title: "Momos", value: "momos", img: img1},
    {title: "Khichdi", value: "khichdi", img: img4},
    {title: "Vada Pav", value: "vada pav", img: img8},
    {title: "Kachori", value: "kachori", img: img7},
    {title: "Chaach", value: "chaach", img: img5},
    {title: "Cold Coffee", value: "cold coffee", img: img9},
    {title: "Upma", value: "upma", img: img6},
    {title: "Soup", value: "soup", img: img6},
    {title: "Poori Bhaji", value: "poori bhaji", img: img6},
    {title: "Aloo Poori", value: "aloo poori", img: img6},
    {title: "Bhel", value: "bhel", img: img6},
    {title: "Masala Maggi", value: "masala maggi", img: img6},
    {title: "Cookies", value: "cookies", img: img6},
    {title: "Dabeli", value: "dabeli", img: img6},
    {title: "Pakoda", value: "pakoda"},
    {title: "Korma", value: "korma"},
    {title: "Hot Dog", value: "hot dog"},
    {title: "Poha", value: "poha"},
    {title: "Thepla", value: "thepla"},
    {title: "Aloo Tikki", value: "aloo tikki"},
    {title: "Parotta", value: "parotta"},
    {title: "Falooda", value: "falooda"},
    {title: "Ramen", value: "ramen"},
    {title: "Cake", value: "cake"},
    {title: "Burger", value: "burger"},
    {title: "Sandwich", value: "sandwich"},
    {title: "Paneer", value: "paneer"},
    {title: "Idli", value: "idli"},
    {title: "Noodles", value: "noodles"},
    {title: "Paratha", value: "paratha"},
    {title: "Ice Cream", value: "ice cream"},
    {title: "Chaat", value: "chaat"},
    {title: "Milkshake", value: "milkshake"},
    {title: "Manchurian", value: "manchurian"},
    {title: "Sev Tamatar", value: "sev tamatar"},
    {title: "Dhokla", value: "dhokla"},
    {title: "Pav Bhaji", value: "pav bhaji"},
    {title: "Samosa", value: "samosa"},
    {title: "Tea", value: "tea"},
    {title: "Juice", value: "juice"},
    {title: "Pasta", value: "pasta"},
    {title: "Coffee", value: "coffee"},
    {title: "Lassi", value: "lassi"},
    {title: "Bread Pakoda", value: "bread pakoda"},
    {title: "Desserts", value: "desserts"},
    {title: "Khaman", value: "khaman"},
    {title: "Salad", value: "salad"},
    {title: "Gulab Jamun", value: "gulab jamun"},
    {title: "Rasmalai", value: "rasmalai"},
    {title: "Sev Khamani", value: "sev khamani"},
    {title: "Pancake", value: "pancake"},
    {title: "Jalebi", value: "jalebi"},
    {title: "Panipuri", value: "panipuri"},
    {title: "Fafda", value: "fafda"},
    {title: "Chocolate", value: "chocolate"},
]